### ISSUE TITLE
python3 not found

### ISSUE THREAD

**Issue by Richard-Payne** [networkboot/docker-dhcpd#1]
When I try to run this image, either with docker-compose up or docker run, I get the following:

/entrypoint.sh: /sbin/my_init: /usr/bin/python3: bad interpreter: No such file or directory
/entrypoint.sh: line 55: /sbin/my_init: Success

I modified the entrypoint to give me a bash shell and tried run the entrypoint.sh script manually with the same result.

Sure enough, there is no /usr/bin/python3.

I noticed that you're doing a dist-upgrade as part of the Dockerfile.  Is this possibly using a new version of python than you were expecting?

**Comment by Richard-Payne** [comment]
root@server:/# whereis python
python: /usr/lib/python2.7

**Comment by Richard-Payne** [comment]
Which would seem to indicate that it's not getting a newer version that you were expecting.

**Comment by Richard-Payne** [comment]
Ah, and:

root@server:/# whereis python3
python3: /usr/lib/python3

**Comment by robinsmidsrod** [comment]
I don't think the init script requires python3. If you have some time to test it with normal /usr/bin/python and see if it works as expected, I'm more than willing to accept a patch.

Also, the entry point is made so that you can just specify /bin/bash to get into a shell, you shouldn't need to modify the entrypoint, AFAIK. It's been a while since I looked at this image, so my memory is a bit hazy.

**Comment by pelgrim** [comment]
Hi!
The same problem happened to me. I solved it by including python3 on the Dockerfile, line #7.

I'm no expert on Docker, and haven't done the proper tests yet. However, I think that it is something regarding the base docker image (ubuntu). Maybe something has changed since you first wrote this image.

**Comment by robinsmidsrod** [comment]
@pelgrim Yeah, my guess too. Thanks for finding the correct package to include. Would you care to send a pull request for that change you suggested?

**Comment by pelgrim** [comment]
@robinsmidsrod Sure! There it is. I hope it works for everybody else. I tested in my testing environment and it worked just fine. Thank you for asking!

**Comment by robinsmidsrod** [comment]
Hopefully everything works for everyone now.
