### ISSUE TITLE
Multi-arch builds in Dockerhub

### ISSUE THREAD

**Issue by thrau** [networkboot/docker-dhcpd#23]
it would be great if this docker image could be pushed to Dockerhub with a [multi-arch manifest](https://dev.to/toolboc/publish-multi-arch-docker-images-to-a-single-repo-with-docker-manifests-329n).
this would be very useful, because it allows us to run `docker pull networkboot/docker-dhcpd` on, e.g., a raspi running hypriot, and it would run out of the box (currently that doesn't work because there are only amd64 builds on Dockerhub, and starting the container fails as expected).

There are multiple ways to create multi-arch images from an x86 machine. One way is using the `buildx` plugin [1].
Another (I think outdated way) is to use qemu have multiple Dockerfiles for each arch and then building a manifest manually [2], which I saw was removed in d58f4356.

  [1]: https://engineering.docker.com/2019/04/multi-arch-images/
  [2]: https://ownyourbits.com/2018/06/27/running-and-building-arm-docker-containers-in-x86/

any chance we can get arm32 & aarch64 builds into Dockerhub?

**Comment by robinsmidsrod** [comment]
@thrau I agree that multi-architecture builds would be nice, but the project is currently using the automated build features in Docker Hub to build a new image whenever the git repo changes. Obviously we'd want to continue doing this, both for the assurance that images contain whatever the Dockerfile says it should, but also because of the automation benefits associated with it.

If you were able to submit a PR that maintains this benefit while at the same time introducing multiarch then I think we could get something done.

The reason the commit you mentioned was removed/reverted was because the build previously contained a manually compiled binary, but now it only uses packages from APT repos, which means that building the image locally on your own architecture shouldn't give you any issues.

I have no experience with either of the two methods mentioned, but I'd want to avoid experimental features, mostly because they could be removed or changed, and then the build would break (probably at a time where it's most unfortunate to everyone that uses it).

Looking forward to a PR implemented with these things in mind.

**Comment by wickywaka** [comment]
Any progress on this?

**Comment by robinsmidsrod** [comment]
@waqarrashid33 Unfortunately, no. Since the last comment, Docker Hub automations is a paid-only feature, so GitHub Actions is probably the better choice going forward. I've not used that before, so any help on that topic would be greatly appreciated.

**Comment by berlin4apk** [comment]
After next weekend
I can make a draft PR for the GitHub action create a multi platform docker Image

**Comment by wickywaka** [comment]
@berlin4apk That would be amazing, I am also a bit new to the dockerization stuff.

**Comment by wickywaka** [comment]
@berlin4apk Is this the right path? If you don't have much time, I can give it a try and then you can review it to make sure that its up to the standard.
http://blog.mauriciofreitas.eng.br/docker/2020/12/25/multiarch-docker-build-github-actions-en.html

**Comment by wickywaka** [comment]
Please have a look at the pull request and recommend changes or improvements. @berlin4apk @robinsmidsrod

**Comment by robinsmidsrod** [comment]
It seems like the PR is moving forward. Hopefully we'll have something here soon.

**Comment by robinsmidsrod** [comment]
@wickywaka Thanks for the PR! Now we've got something that builds the docker images automatically. And ARM is supported!
