### ISSUE TITLE
Cannot serve dhcp over the network

### ISSUE THREAD

**Issue by floion** [networkboot/docker-dhcpd#39]
Trying to "docker run" this project and I get:

`You must add the 'docker run' option '--net=host' if you want to provide DHCP service to the host network.`

Does anybody else see this?
cc @robinsmidsrod

**Comment by robinsmidsrod** [comment]
Yes, it's part of the container entrypoint script. Since it's highly unlikely that you want to provide DHCP service to an interface on a non-bridged network, this warning is emitted if you don't specify that you want to use the host network.

Do you have a use-case where this causes a problem?

**Comment by floion** [comment]
But I am running it with "--net=host" and still I get that warning and trying to get a lease from this server does nothing.

**Comment by floion** [comment]
This is how I run it:

```
docker run -d --rm --init --net host -v /tmp/netboot:/data:z networkboot/dhcpd
```

and in `/tmp/netboot` I have my dhcpd.conf

**Comment by robinsmidsrod** [comment]
@floion After reading the docker run documentation, I can't really seem to grasp what that `:z` option at the end of your volume mount means, but have you tried removing it? The `/data` folder must be mounted read-write, because the dhcpd.leases file is stored there, and the dhcp server modifies it during runtime.

It is also normal to specify the interface (on your host network) at the end of the command line that you want to provide DHCP service for, unless you explicitly want to provide DHCP service for all interfaces on the host network (which is somewhat uncommon). I personally prefer to use one configuration and container for each interface I'm controlling.

My personal systemd service unit looks like this, for reference:

```
# systemctl cat dhcpd-lan.service
# /etc/systemd/system/dhcpd-lan.service
[Unit]
Description=ISC DHCP server for lan network (VLAN 1)
BindsTo=sys-subsystem-net-devices-br0.device
After=sys-subsystem-net-devices-br0.device
After=docker.service

[Service]
Type=simple
Restart=always
ExecStartPre=/usr/local/bin/docker-clean %n
ExecStart=/usr/bin/docker run --rm --name %n --init --network host \
 -v /etc/dhcp/lan:/data \
 networkboot/dhcpd:1.3.0 br0
ExecReload=/usr/bin/docker restart %n
SuccessExitStatus=143
RestartSec=5
SyslogIdentifier=%n

[Install]
WantedBy=multi-user.target
```

**Comment by floion** [comment]
@robinsmidsrod the :z is for selinux on my fedora box. See https://stackoverflow.com/questions/35218194/what-is-z-flag-in-docker-containers-volumes-from-option for example

Problem is that a few months ago this worked perfectly, no it does not anymore.

I ran it specifying also the interface I want to run dhcp on and same thing.
It puzzles me

**Comment by robinsmidsrod** [comment]
I don't think this is specifically related to this container, and seems to be a general issue with your docker host. I've never looked into selinux and what kind of additional security requirements it puts on containers, but I'm assuming you need to check what has changed in your system since it last worked. Unless you have any additional details to shed light on this issue, I'm inclined to close it. Feel free to reopen if you have more details.
