### ISSUE TITLE
groupmod: GID '50' already exists

### ISSUE THREAD

**Issue by gadieichhorn** [networkboot/docker-dhcpd#8]
Thanks for this repo!

I am trying to run docker from powershell windows 10 and I am getting this error

> groupmod: GID '50' already exists

My run script is a bit different on windows.

> docker run -it --rm --net=host -v //c/Users/test/data:/data networkboot/dhcpd eth0

I tried with different dhcpd.conf option but all have same error.

**Comment by robinsmidsrod** [comment]
I'm unsure how this would work on Windows, as Docker on Windows usually is virtualized using VirtualBox. I'm unsure how --net=host behaves in that scenario.

But to me it seems like this issue is related to the user actually running the docker command being mapped to group id 50, which is usually a system account. Normal users on Linux systems usually start at uid/gid 1000. You'll need to provide me with more information to figure out exactly what the issue is...

**Comment by gadieichhorn** [comment]
First thank you for the detailed and timely answer.

I run docker toolbox, so it is a virtualbox docker host. I have no other issues like this with any other containers so I suspect this is to do with special interaction between your container and the host.

> docker-machine create -d virtualbox --virtualbox-memory "1024" --virtualbox-cpu-count "1" --virtualbox-disk-size "8000" --engine-storage-driver overlay dhcpd

Will this container conflict with docker internal DHCP, assuming this is how docker manage containers IPs?

Appreciate your help.

**Comment by robinsmidsrod** [comment]
To be honest, I'm not sure if it would even work, as the VirtualBox host networking defaults to NAT, which means that it'll most likely provide DHCP service on the same network as the VirtualBox DHCP server, causing a conflict of service. If you'd like for it to provide DHCP to your local network you probably need to run that VirtualBox with bridged networking, or on a physical Linux host.

**Comment by gadieichhorn** [comment]
Ok, thank you, I believe you are right and this will not work on windows/virtualbox.
Appreciate your time.
